### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by brothermechanic** [sergem155/blender-deshaker-log-import#1]
Hello
I try to import Deshaker.log with your import_deshaker_damper.py script
But i have error

```
Traceback (most recent call last):
  File "/usr/share/blender/2.77/scripts/addons/import_deshaker_damper.py", line 75, in execute
    self.import_deshaker_file(context, self.filepath) 
  File "/usr/share/blender/2.77/scripts/addons/import_deshaker_damper.py", line 121, in import_deshaker_file
    for (kf,x,y,r,new_scene) in value_generator(filepath,xdamp,ydamp,rdamp):
  File "/usr/share/blender/2.77/scripts/addons/import_deshaker_damper.py", line 52, in value_generator
    xi = float(a[1])
ValueError: could not convert string to float: 'skipped'

location: <unknown location>:-1
```

Deshaker.log + videofiles 
[files.zip](https://github.com/sergem155/blender-deshaker-log-import/files/350257/hacks.zip)

**Comment by sergem155** [comment]
Hi brothermechanic,

Thanks for the clear issue report!

I added a line to ignore skipped frames, but I recommend adjusting Deshaker
tracking settings so there is as fewer skipped frames as possible (perhaps
use every pixel, use larger tracking blocks, things like that).

The log file you've sent now imports fine, but because there is no tracking
info for skipped frames, it results in quite jerky video every now and then.

Best regards
Sergey

On Wed, Jul 6, 2016 at 8:44 AM, brothermechanic notifications@github.com
wrote:

> Hello
> I try to import Deshaker.log with your import_deshaker_damper.py script
> But i have error
> 
> Traceback (most recent call last):
>   File "/usr/share/blender/2.77/scripts/addons/import_deshaker_damper.py", line 75, in execute
>     self.import_deshaker_file(context, self.filepath)
>   File "/usr/share/blender/2.77/scripts/addons/import_deshaker_damper.py", line 121, in import_deshaker_file
>     for (kf,x,y,r,new_scene) in value_generator(filepath,xdamp,ydamp,rdamp):
>   File "/usr/share/blender/2.77/scripts/addons/import_deshaker_damper.py", line 52, in value_generator
>     xi = float(a[1])
> ValueError: could not convert string to float: 'skipped'
> 
> location: <unknown location>:-1
> 
> Deshaker.log + videofiles
> files.zip
> https://github.com/sergem155/blender-deshaker-log-import/files/350257/hacks.zip
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/sergem155/blender-deshaker-log-import/issues/1, or mute
> the thread
> https://github.com/notifications/unsubscribe/ANPEyTFKR886XY-LMYE-yyrC59mfWM1Xks5qS81HgaJpZM4JGN-u
> .

## 

Best regards,
Sergey Menshikov
Product Manager

_Bright Pattern, Inc_
http://www.brightpattern.com
tel: 415-938-7204

**Comment by brothermechanic** [comment]
Hello
Thank's. It's loks like works!
http://i.imgur.com/EtlLsRa.png
Do you mean as skipped frames this missing keyframes in blender's Dope Sheet?
Now i try follow your dawice.
Can you check my new deshaker's config http://i.imgur.com/1pceRnw.png? 
Is it possible create deshaker's log in comand line mode?

Anyway, this is GREAT script, because, deshaker is best free stabiliser. Now i test it with real videos
Thank you.

**Comment by brothermechanic** [comment]
Ok
This is my tests https://yadi.sk/d/irnPFsL8t7ZEB
test-01-orig.3gp - is video from smartphone
test-01-transcode.mpeg - transcoded to hd1080 and 25fps mpeg2 (for Vdub input)
test-01-VDub-output.avi - stabilised in VDub. Nise stab!
test-01-Blender-output.mov - stabilised in Blender. Bad stab (((
As you can see - blender's video is mutch worse!
You can test my blender's timeline and find how to improve your's script.
May be it helps
Thank you.

**Comment by sergem155** [comment]
brothermechanic,

Settings look OK, perhaps increase diff search range - look at explanation
in http://www.guthspot.se/video/deshaker.htm

Re: deshaker vs blender damping - I think you used the same transcoded file
in Blender timeline and for deshaker analysis: in Blender the scene is at
50% scale by default, so all deshaker data was multiplied by two, which
resulted in exaggerated movements.

If you increase the scale in Blender render properties to 100%, or use 50%
render result for deshaker analysis, it should work fine.

Finally, make sure you use the damper version of the script. Tweak
dampening functions in the source to make it more/less aggressive.

I hope this helps.
